/**
 * @nimbus-dev/client — MIT local Gateway client (IPC).
 */

// Re-exported so consumers (nimbus-vscode) can name the item shape without
// taking a direct dependency on @nimbus-dev/sdk.
export type {
  AgentBrief,
  AgentName,
  BriefFor,
  CatchupBrief,
  ConflictBrief,
  ExpertBrief,
  GhostBrief,
  HuddleBrief,
  ImpactBrief,
  JanitorBrief,
  NimbusItem,
  PreflightBrief,
  WhyBrief,
  WhyFinding,
  WhyLane,
  WhyPeek,
  WhySubject,
} from "@nimbus-dev/sdk";
export {
  AgentBriefError,
  type AgentBriefEvent,
  type AgentParamsFor,
  AgentTimeoutError,
  type CatchupParams,
  type ConflictsParams,
  DEFAULT_AGENT_TIMEOUT_MS,
  type ExpertParams,
  type GhostParams,
  type HuddleParams,
  type ImpactParams,
  type JanitorParams,
  type PreflightParams,
  type WhyParams,
} from "./agents.js";
export {
  discoverSocketPath,
  type GatewayStateFile,
  gatewayStatePath,
  readGatewayState,
  type SocketDiscoveryResult,
} from "./discovery.js";
export { IPCClient, type IPCClientOptions } from "./ipc-transport.js";
export { MockClient, type MockClientFixtures } from "./mock-client.js";
export {
  type AuditStatus,
  type AuditSummary,
  type AuditToolCallsParams,
  type AuditToolCallsResult,
  type AuditVerifyParams,
  type AuditVerifyResult,
  type CiFinding,
  type ConnectorAddMcpParams,
  type ConnectorAddMcpResult,
  type ConnectorAuthParams,
  type ConnectorAuthResult,
  type ConnectorHealthEntry,
  type ConnectorHealthHistoryEntry,
  type ConnectorHealthHistoryParams,
  type ConnectorReindexParams,
  type ConnectorReindexResult,
  type ConnectorRemoveParams,
  type ConnectorRemoveResult,
  type ConnectorServiceParams,
  type ConnectorSetConfigParams,
  type ConnectorSetConfigResult,
  type ConnectorSetIntervalParams,
  type ConnectorStatus,
  type ConnectorStatusParams,
  type ConnectorStatusResult,
  type ConnectorSyncParams,
  type ConnectorSyncStatus,
  type ConnectorSyncTelemetry,
  type ConsentRespondParams,
  type DeployPreflightParams,
  type DeployPreflightResult,
  type DiagSnapshot,
  type DiagVersion,
  type DoraGap,
  type DoraMetricsResult,
  type DoraMetricValue,
  type EgressCompleteness,
  type EgressHead,
  type EgressListParams,
  type EgressListResult,
  type EgressProveWindowParams,
  type EgressProveWindowResult,
  type EgressReceipt,
  type EgressRow,
  type EgressVerifyResult,
  type GatedRejection,
  type GatewayPingResult,
  type GatewayStatus,
  type HitlStatusCounts,
  type IdentityStatus,
  type IncidentFinding,
  type IndexedItem,
  type IndexMetrics,
  type MetricsDoraParams,
  type NamespaceStatus,
  NimbusClient,
  type NimbusClientLike,
  type NimbusClientOptions,
  type PeerStatus,
  type PolicySource,
  type PolicyState,
  type PreflightCheck,
  type PreflightGap,
  type PrFinding,
  type RankedSearchItem,
  type RankedSearchParams,
  type SandboxDiag,
  type SessionAppendParams,
  type SessionClearParams,
  type SessionClearResult,
  type SessionListEntry,
  type SessionListResult,
  type SessionMemoryRole,
  type SessionRecallHit,
  type SessionRecallParams,
  type SessionRecallResult,
  type SessionTranscript,
  type ToolCallLogEntry,
  type WatcherSummary,
  type WorkflowDeleteParams,
  type WorkflowListResult,
  type WorkflowListRunsParams,
  type WorkflowListRunsResult,
  type WorkflowRow,
  type WorkflowRunHistoryRow,
  type WorkflowRunParams,
  type WorkflowRunResult,
  type WorkflowSaveParams,
  type WorkflowStepResult,
} from "./nimbus-client.js";
export { getNimbusPaths, type NimbusPaths } from "./paths.js";
export type {
  AskStreamHandle,
  AskStreamOptions,
  HitlRequest,
  StreamEvent,
} from "./stream-events.js";
export { IpcResponseError } from "./validate.js";
